### PR TITLE
more @codahq changes

### PR DESCRIPTION
**Pull request by codahq**
+ fixed CRON another way
+ added a way to reset the boot loop counter
+ totally unnecessary styling changes (credit Adam for the cool artwork)

### CODE REVIEW

**Comment by codahq** [comment]
if you're getting sick of me or if you feel like i'm taking over your app...  PLEASE feel free to shoot this down.

**Comment by adamkempenich** [comment]
Changes look good. I might put the PNG back in but it's not necessary (obviously).

**Comment by adamkempenich** [comment]
Keep the PRs coming! :)

**Comment by codahq** [comment]
I used the PNG from the community post. I was trying to figure out a way to use both. Maybe I'll put the small one on the reset page?

**Comment by adamkempenich** [comment]
Probably not worth the time. It looks good as is :) Thanks for swapping it!

**Pull request merged**
